version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ecomm_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
    ports:
      - "5433:5432"
